// <auto-generated />
using System;
using EcommerceRopa.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceRopa.Migrations
{
    [DbContext(typeof(DBCrudContext))]
    partial class DBCrudContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EcommerceRopa.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Departamento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Existencia")
                        .HasColumnType("int");

                    b.Property<int?>("PrendaId")
                        .HasColumnType("int")
                        .HasColumnName("PrendaID");

                    b.HasKey("Id");

                    b.HasIndex("PrendaId");

                    b.ToTable("Inventario", (string)null);
                });

            modelBuilder.Entity("EcommerceRopa.Models.Prenda", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estilo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Talla")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Prenda");
                });

            modelBuilder.Entity("EcommerceRopa.Models.Inventario", b =>
                {
                    b.HasOne("EcommerceRopa.Models.Prenda", "Prenda")
                        .WithMany("Inventarios")
                        .HasForeignKey("PrendaId")
                        .HasConstraintName("FK__Inventari__Prend__398D8EEE");

                    b.Navigation("Prenda");
                });

            modelBuilder.Entity("EcommerceRopa.Models.Prenda", b =>
                {
                    b.Navigation("Inventarios");
                });
#pragma warning restore 612, 618
        }
    }
}
